### PR TITLE
Fix negative overflow, add interpolation test.

### LINKED ISSUE #51: Integer underflow in `interpolate`.
Only reproducible without `--release`, which requires mocktography, or a lot of spare time. Output:

```
thread 'drop_and_readd' panicked at 'attempt to subtract with overflow', /home/marc/.cargo/git/checkouts/threshold_crypto-3605c1a1492f376b/20de873/src/lib.rs:600:17
thread 'drop_and_readd' panicked at 'Test failed: attempt to subtract with overflow; minimal failing input: cfg = TestConfig { dimension: NetworkDimension { size: 1, faulty: 0 }, total_txs: 20, batch_size: 10, contribution_size: 1, seed: [3923024402, 3609989464, 4075880450, 1102868230] }
	successes: 0
	local rejects: 0
	global rejects: 0
', tests/net_dynamic_hb.rs:78:1
```

`hbbft`: 6df72d86cc109538f69511be5e562e257b7fb2e0

### PR DESCRIPTION
**Pull request by afck**
Closes #51.

### CODE REVIEW

**Comment by c0gent** [comment]
Keep in mind that this isn't actually an underflow issue (which is related to precision). This is negative overflow.

File: src/lib.rs [hunk 1]
```diff
@@ -632,7 +637,24 @@ mod tests {
...
+
+    #[test]
+    fn test_interpolate() {
+        let mut rng = rand::thread_rng();
+        for deg in 0..5 {
+            println!("deg = {}", deg);
+            let comm = Poly::random(deg, &mut rng).commitment();
+            let mut values = Vec::new();
+            let mut x = 0;
+            for _ in 0..(deg + 1) {
```
Comment (DrPeterVanNostrand) [inline src/lib.rs]: I'm a horrible person... but `0..=deg` ?

Comment (afck) [reply src/lib.rs]: No, you're right. :smile: 
I amended the commit:

```diff
-            for _ in 0..(deg + 1) {
+            for _ in 0..=deg {
```
